[package]
name = "chap20_webserver"
version = "0.1.0"
authors = ["Amry Amanah <amry.amanah@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
